# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{autometal-piwik}
  s.version = "0.6.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Achillefs Charmpilas", "mihael"]
  s.date = %q{2013-01-05}
  s.description = %q{Provides simple access to the Piwik API.}
  s.email = %q{ac@humbuckercode.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "autometal-piwik.gemspec",
    "lib/piwik.rb",
    "lib/piwik/base.rb",
    "lib/piwik/site.rb",
    "lib/piwik/trackable.rb",
    "lib/piwik/user.rb",
    "script/console",
    "test/files/config/example_piwik.yml",
    "test/piwik_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{https://github.com/Achillefs/autometal-piwik}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{A ruby client for the Piwik API.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.9"])
      s.add_runtime_dependency(%q<rest-client>, [">= 1.6.1"])
      s.add_runtime_dependency(%q<json>, [">= 1.4.6"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0.9"])
      s.add_dependency(%q<rest-client>, [">= 1.6.1"])
      s.add_dependency(%q<json>, [">= 1.4.6"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0.9"])
    s.add_dependency(%q<rest-client>, [">= 1.6.1"])
    s.add_dependency(%q<json>, [">= 1.4.6"])
  end
end

